version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["gunicorn", "chorema.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - chorema-postgres

  chorema-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chorema_db
      POSTGRES_USER: chorema_user
      POSTGRES_PASSWORD: chorema_password

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/app/dist:/usr/share/nginx/html
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume: