# Generated by Django 4.2.6 on 2023-11-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0002_alter_userprofile_options_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='done_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='done_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
